/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 1395841d70d802c86115ea84ea739491)
interface __BaseEnv_Env {
	DB: D1Database;
	VECTOR_INDEX: VectorizeIndex;
	AI: Ai;
	ASSETS: Fetcher;
	RATE_LIMIT_GLOBAL_PER_HOUR: "100";
	RATE_LIMIT_SESSION_PER_HOUR: "3";
	RATE_LIMIT_EMAIL_PER_HOUR: "3";
	MAX_HISTORY_MESSAGES: "20";
	OPENAI_API_KEY: string;
	OPENAI_MODELS: string;
	OPENAI_GUARDRAIL_MODELS: string;
	LANGSMITH_TRACING: string;
	LANGSMITH_ENDPOINT: string;
	LANGSMITH_API_KEY: string;
	LANGSMITH_PROJECT: string;
	LOGGER_LEVEL: string;
	LOGGER_FORMAT: string;
	Chat: DurableObjectNamespace<import("./src/server").Chat>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RATE_LIMIT_GLOBAL_PER_HOUR" | "RATE_LIMIT_SESSION_PER_HOUR" | "RATE_LIMIT_EMAIL_PER_HOUR" | "MAX_HISTORY_MESSAGES" | "OPENAI_API_KEY" | "OPENAI_MODELS" | "OPENAI_GUARDRAIL_MODELS" | "LANGSMITH_TRACING" | "LANGSMITH_ENDPOINT" | "LANGSMITH_API_KEY" | "LANGSMITH_PROJECT" | "LOGGER_LEVEL" | "LOGGER_FORMAT">> {}
}
