/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 5eb65393569925f7e0b9f7df004fe83c)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		OPENAI_API_KEY: string;
		OPENROUTER_API_KEY: string;
		OPENROUTER_SITE_URL?: string;
		OPENROUTER_SITE_NAME?: string;
		OPENROUTER_MODELS: string;
		OPENROUTER_GUARDRAIL_MODELS: string;
		LANGSMITH_TRACING: string;
		LANGSMITH_ENDPOINT: string;
		LANGSMITH_API_KEY: string;
		LANGSMITH_PROJECT: string;
		RATE_LIMIT_GLOBAL_PER_HOUR?: string;
		RATE_LIMIT_SESSION_PER_HOUR?: string;
		RATE_LIMIT_EMAIL_PER_HOUR?: string;
		MAX_HISTORY_MESSAGES?: string;
		LOG_LEVEL?: string;
		LOG_FORMAT?: 'json' | 'pretty';
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		DB: D1Database;
		VECTOR_INDEX: VectorizeIndex;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY" | "OPENROUTER_API_KEY" | "OPENROUTER_SITE_URL" | "OPENROUTER_SITE_NAME" | "OPENROUTER_MODELS" | "OPENROUTER_GUARDRAIL_MODELS" | "LANGSMITH_TRACING" | "LANGSMITH_ENDPOINT" | "LANGSMITH_API_KEY" | "LANGSMITH_PROJECT">> {}
}
