/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: d7f72bdc0dfb0fe96df1ab4014cf5d51)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		OPENAI_API_KEY: string;
		LANGSMITH_TRACING: string;
		LANGSMITH_ENDPOINT: string;
		LANGSMITH_API_KEY: string;
		LANGSMITH_PROJECT: string;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		DB: D1Database;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY" | "LANGSMITH_TRACING" | "LANGSMITH_ENDPOINT" | "LANGSMITH_API_KEY" | "LANGSMITH_PROJECT">> {}
}
